{- |
- Module      :  $Header$
- Description :  The tempuhs web server Cabal setup file.
- Copyright   :  (c) plaimi 2015
- License     :  AGPL-3
-
- Maintainer  :  tempuhs@plaimi.net
- -}

import Control.Exception
  (
  catch,
  )
import Data.Text
  (
  pack,
  toTitle,
  unpack,
  )
import Distribution.Simple
  (
  defaultMainWithHooks,
  preBuild,
  simpleUserHooks,
  )
import System.Exit
  (
  ExitCode (ExitSuccess),
  )
import System.IO.Error
  (
  isAlreadyExistsError,
  ioeGetErrorString,
  )
import System.Posix
  (
  createDirectory,
  )
import System.Process
  (
  rawSystem,
  )
import Text.Printf
  (
  printf,
  )

import Plailude

main :: IO ()
-- | Generates data/src.tar.gz for us pre-building, so we can serve the source
-- code of the instance.
main = defaultMainWithHooks
     $ simpleUserHooks
       { preBuild = \args buildFlags -> do
         createDirectory "data" 0o755 `catch` \e ->
           if' (isAlreadyExistsError e)
             (return ())
             (printf ("couldn't make the data directory: %s\n"
                  ++ "please do it yourself. we need it!") $
              unpack . toTitle . pack $ ioeGetErrorString e)
         exitCode <- rawSystem "tar" $ tarOut ++ tarIn
         putStrLn $ echoOut exitCode
         preBuild simpleUserHooks args buildFlags
       }

tarOut :: [String]
-- | The file generated by tar.
tarOut =  ["cfz", "data/src.tar.gz"]

tarIn :: [String]
-- | The files passed to tar.
tarIn = ["Setup.hs"
             ,"tempuhs-server.cabal"
             ,"prop"
             ,"src"
             ,"src-exec"
             ,"test"
             ]

echoOut :: ExitCode -> String
-- | Make an output text to echo, depending on the passed in 'ExitCode'.
echoOut ExitSuccess = "'put src in data/src.tar.gz'"
echoOut _           = "'uh-oh! couldn't make a gzipped tarball of the src! "
                   ++ "you need to put the src of your tempuhs instance in a "
                   ++ "file \"data/src.tar.gz\" before building. this is to "
                   ++ "comply with the GNU AGPLv3."
